name: "Django Multitenant Tests"
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: actions/checkout@v4
    - name: Install python dependencies
      run: |
        pip install -r requirements/static-analysis-requirements.txt
    - name: Format Checks
      run: |
        make format-check
    - name: Prospector checks
      run: |
        make lint

    - name: Documentation Checks
      run: |
        cd docs
        sphinx-build -W -b html source builds

  tests:
    runs-on: ubuntu-latest
    name: "Python: ${{matrix.python_version}} | Django: 6.0 | Citus: ${{matrix.citus_version}}"
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.12","3.13"]
        citus_version: ["12","13"]
    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      CITUS_VERSION: ${{ matrix.citus_version }}
      DJANGO_VERSION: "6.0"
    steps:
    - uses: actions/checkout@v4
    - name: Test Django MT
      run: |
        docker compose --project-name django-multitenant up -d || { docker compose logs && false ; }
        echo "Running tests for python $PYTHON_VERSION, django $DJANGO_VERSION, citus $CITUS_VERSION"
        docker run \
        --entrypoint /build/scripts/test-django-mt.sh \
        -v $(pwd):/build \
        --network django-multitenant_default \
        -e PYTHON_VERSION -e DJANGO_VERSION \
        -e DATABASE_HOST=django-multitenant_master \
        -e DATABASE_PORT=5432 \
        citusdata/python-all-versions
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
    - name: Test Missing Modules
      run: |
        echo "Running tests for python $PYTHON_VERSION, django $DJANGO_VERSION, citus $CITUS_VERSION"
        docker run \
        --entrypoint /build/scripts/test-django-mt-modules.sh \
        -v $(pwd):/build \
        --network django-multitenant_default \
        -e PYTHON_VERSION -e DJANGO_VERSION \
        -e DATABASE_HOST=django-multitenant_master \
        -e DATABASE_PORT=5432 \
        citusdata/python-all-versions
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
